### ISSUE TITLE
Server.host does not allow ending '/'

### ISSUE THREAD

**Issue by emepetres** [MSO4SC/cloudify-im-extension#3]
If the Server host ends with '/', the extension fails.

**Comment by victorsndvg** [comment]
I'm not going to fix this. The plugin cannot change the provided URI's. Provided URIS have to be valid. See docs:

https://imdocs.readthedocs.io/en/latest/radl.html

**Comment by emepetres** [comment]
But it is the extension the one which is building the complete URIs. Even if it doesn't, it has the possibility to do some validity checks while building the radle, like the one mention in this issue.

I'll reopen again for reference, although as you said it is not going to be implemented at the moment.

**Comment by victorsndvg** [comment]
Valid URIs cannot be decided by the plugin. It depends on the host. What we can try to improve is exception caching if you prefer
