### ISSUE TITLE
software type -> Server.context

### ISSUE THREAD

**Issue by emepetres** [MSO4SC/cloudify-im-extension#7]
Maybe the 'software' object is a little bit confusing.

If it is representing a virtual machine context, or a bootstrap of a virtual machine, I think it shouldn't be an independent object, but a property of Server.

**Comment by victorsndvg** [comment]
The strategy to code this plugin was to map the RADL basic structure. That is the specification behind the Infrastructure Manager middleware. See the docs:
https://imdocs.readthedocs.io/en/latest/radl.html

**Comment by emepetres** [comment]
Ok but at least, why naming it "software" instead of "context"/"contextualization"?

This doesn't have much importance right now, but it is worth mention.

**Comment by victorsndvg** [comment]
Ok, let me be more specific here. Maybe the name of the node type can be improved, but contextualization is much more generic that what the plugin can do with this kind of nodes. 

In my opinion, to call it contextualization we should completely wrap `ansible` contextualization.

What the plugin supports right now is to install software packages by means of `yum` and to run shell scripts. Shell scripts can be quite powerful, but doing complex things from shell scripts in an unknown environment can be very complicated by developer users. As developers what the better know how to do is to install their software. Of course, this happens during contextualization.

This part of the plugin is based in the following ansible features:
https://docs.ansible.com/ansible/latest/modules/yum_module.html
https://docs.ansible.com/ansible/latest/modules/shell_module.html

A list of all ansible modules is here:
https://docs.ansible.com/ansible/latest/modules/list_of_all_modules.html

Do you suggest any other name?
